### ISSUE TITLE
[ 问题咨询 ]执行慢查询脚本报错，求指点，谢谢！

### ISSUE THREAD

**Issue by sunsky-cn** [hhyo/Archery#931]
Pipeline process 6 (iteration) caused an error: DBD::mysql::st execute failed: MySQL server has gone away [for Statement "      INSERT INTO `archery`.`mysql_slow_query_review`
      (checksum, fingerprint, sample, first_seen, last_seen)
      VALUES(?, ?, ?, COALESCE(?, NOW()), COALESCE(?, NOW()))
      ON DUPLICATE KEY UPDATE
         first_seen = IF(
            first_seen IS NULL,
            COALESCE(?, NOW()),
            LEAST(first_seen, COALESCE(?, NOW()))),
         last_seen = IF(
            last_seen IS NULL,
            COALESCE(?, NOW()),
            GREATEST(last_seen, COALESCE(?, NOW())))
" with ParamValues: 0='31D6B1B32DF42984ED410BBDDAB6A1F7', 1='replace into `molbase_us`.`search_molstruc`(`struc`,`sub_pid`,`sm_pid`,`mol_id`) values(?+)', 2='replace into `molbase_us`.`search_molstruc`(`struc`,`sub_pid`,`sm_pid`,`mol_id`) VALUES (x'202066726F6D206D6F6C626173652E636F6D0A20206361733A313233363330302D36332D32206D6F6C69643A31313538313934390A202074696D653A323031372D31312D30372030353A31303A31320A2031312031322020302020332020302020202020202020202020202020203939392056323030300A20202020312E3733333620202020312E3439383620202020302E303030302043202020302030302020302020302020302020302020302020302020302020302020302020300A20202020312E3733333620202020302E3439393520202020302E303030302043202020302030302020302020302020302020302020302020302020302020302020302020300A20202020322E3638333920202020312E3830383620202020302E303030302043202020302020302020302020302020302020302020302020302020302020302020302020300A20202020302E3836373420202020312E3939383220202020302E303030302043202020302030302020302020302020302020302020302020302020302020302020302020300A20202020322E3638333920202020302E3139333020202020302E3030303020432020203020203020203020203020203020203020...', 3='2020-09-25 11:11:14', 4='2020-09-25 13:17:39', 5='2020-09-25 11:11:14', 6='2020-09-25 11:11:14', 7='2020-09-25 13:17:39', 8='2020-09-25 13:17:39'] at /usr/bin/pt-query-digest line 9325.
Will retry pipeline process 5 (iteration) 2 more times.
Pipeline process 6 (iteration) caused an error: DBD::mysql::st execute failed: MySQL server has gone away [for Statement "SELECT `first_seen`, `last_seen`, `reviewed_by`, `reviewed_on`, `comments`, `reviewed_status`, checksum AS checksum_conv FROM `archery`.`mysql_slow_query_review` WHERE checksum=?" with ParamValues: 0='42C9CF3B109256973B0E2284BBB1B994'] at /usr/bin/pt-query-digest line 9312.
Will retry pipeline process 5 (iteration) 1 more time.
The pipeline caused an error: Pipeline process 6 (iteration) caused an error: DBD::mysql::st execute failed: MySQL server has gone away [for Statement "SELECT `first_seen`, `last_seen`, `reviewed_by`, `reviewed_on`, `comments`, `reviewed_status`, checksum AS checksum_conv FROM `archery`.`mysql_slow_query_review` WHERE checksum=?" with ParamValues: 0='42C9CF3B109256973B0E2284BBB1B994'] at /usr/bin/pt-query-digest line 9312.
Terminating pipeline because process 5 (iteration) caused too many errors.

**Comment by hhyo** [comment]
`MySQL server has gone away `

检查一下max_allowed_packet

**Comment by sunsky-cn** [comment]
确实是max_allowed_packet导致，谢谢！

**Comment by Ants5** [comment]
修改了max_allowed_pa​​cket值以后，还是会出现这样的报错，求指点，谢谢1
Pipeline process 6 (iteration) caused an error: DBD::mysql::st execute failed: MySQL server has gone away [for Statement "      INSERT INTO `archery`.`mysql_slow_query_review`
      (checksum, fingerprint, sample, first_seen, last_seen)
      VALUES(?, ?, ?, COALESCE(?, NOW()), COALESCE(?, NOW()))
      ON DUPLICATE KEY UPDATE
         first_seen = IF(
            first_seen IS NULL,
            COALESCE(?, NOW()),
            LEAST(first_seen, COALESCE(?, NOW()))),
         last_seen = IF(
            last_seen IS NULL,
            COALESCE(?, NOW()),
            GREATEST(last_seen, COALESCE(?, NOW())))
" with ParamValues: 0='416639C290E63B85F16C3E7609C01D7E', 1='select country_code as countrycode, province_code as provincecode, city_code as citycode, city_name as cityname, zipcodes as zipcodes from city_info where ( match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or match (zipcodes) against(?) or m...', 2='select country_code  as countryCode,
        province_code as provinceCode,
        city_code     as cityCode,
        city_name     as cityName,
        zipcodes      as zipcodes
        from city_info
        where
         (  
            MATCH (zipcodes) against('4820-000')
         or 
            MATCH (zipcodes) against('4820-002')
         or 
            MATCH (zipcodes) against('4820-004')
         or 
            MATCH (zipcodes) against('4820-006')
         or 
            MATCH (zipcodes) against('4820-008')
         or 
            MATCH (zipcodes) against('4820-009')
         or 
            MATCH (zipcodes) against('4820-098')
         or 
            MATCH (zipcodes) against('4820-099')
         or 
            MATCH (zipcodes) against('4820-100')
         or 
            MATCH (zipcodes) against('4820-101')
         or 
            MATCH (zipcodes) against('4820-102')
         or 
            MATCH (zipcodes) against('4820-103')
         or 
            MATCH (zi...', 3='2021-12-09T04:33:23', 4='2021-12-09T06:14:19', 5='2021-12-09T04:33:23', 6='2021-12-09T04:33:23', 7='2021-12-09T06:14:19', 8='2021-12-09T06:14:19'] at /usr/bin/pt-query-digest line 9326.
Will retry pipeline process 5 (iteration) 2 more times.
Pipeline process 6 (iteration) caused an error: DBD::mysql::st execute failed: MySQL server has gone away [for Statement "SELECT `first_seen`, `last_seen`, `reviewed_by`, `reviewed_on`, `comments`, `reviewed_status`, checksum AS checksum_conv FROM `archery`.`mysql_slow_query_review` WHERE checksum=?" with ParamValues: 0='6806D597061B4B6472B98F2B00EE497A'] at /usr/bin/pt-query-digest line 9313.
Will retry pipeline process 5 (iteration) 1 more time.
The pipeline caused an error: Pipeline process 6 (iteration) caused an error: DBD::mysql::st execute failed: MySQL server has gone away [for Statement "SELECT `first_seen`, `last_seen`, `reviewed_by`, `reviewed_on`, `comments`, `reviewed_status`, checksum AS checksum_conv FROM `archery`.`mysql_slow_query_review` WHERE checksum=?" with ParamValues: 0='6806D597061B4B6472B98F2B00EE497A'] at /usr/bin/pt-query-digest line 9313.
Terminating pipeline because process 5 (iteration) caused too many errors.
